# Generated by Django 2.2.19 on 2025-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20250423_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='Пусто'),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='Пусто'),
        ),
    ]
